// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_airbnb_clone.Data;

#nullable disable

namespace api_airbnb_clone.Migrations
{
    [DbContext(typeof(IconsDBContext))]
    partial class IconsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_airbnb_clone.Models.Icons", b =>
                {
                    b.Property<int>("IconsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IconsId"));

                    b.Property<string>("IconsDesign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IconsId");

                    b.ToTable("Icones");
                });
#pragma warning restore 612, 618
        }
    }
}
